import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { OPERATION_DIGEST_TAG } from './digest.js';
import { generateVectors, VECTOR_SCHEMA_VERSION } from './vectors.js';

const target = path.resolve(import.meta.dirname, '../vectors/operation-digests.json');
const vectors = generateVectors();
const payload = {
  schemaVersion: VECTOR_SCHEMA_VERSION,
  digestTag: OPERATION_DIGEST_TAG,
  // Explicit count: Foundry cannot read an array length from a JSON path directly.
  count: vectors.length,
  note: 'Generated by @cag/receipts. Read by BOTH the TypeScript and Foundry suites so neither side can be fixed to match itself. Regenerate with: pnpm --filter @cag/receipts vectors',
  vectors,
};
writeFileSync(target, `${JSON.stringify(payload, null, 2)}\n`);
process.stdout.write(`wrote ${payload.vectors.length} vectors to ${target}\n`);
