import type { Metadata } from 'next';
import { AppShell } from '../../components/app-shell';
import replay from '../../lib/b20-replay.json';

/**
 * The B20 split replay.
 *
 * One screen, one question: what do three integrations say about the same holding at the same
 * moment, after a 10:1 split?
 *
 * Everything rendered here comes from `apps/web/src/lib/b20-replay.json`, which is generated
 * by `scripts/b20-e2e-proof.mjs` from a live Base mainnet read plus a replayed split. It is
 * labelled RECORDED REPLAY at the top of the page and again beside the split, because a demo
 * that quietly presented a replay as live production state would be committing the exact
 * class of error this product exists to catch.
 *
 * There is a reason it is a replay rather than a live read. No Coinbase asset has had a
 * corporate action yet — every one reads `multiplier() == 1.0` — so a live screen would show
 * three identical, correct answers and demonstrate nothing. The replay shows the divergence
 * the moment one happens.
 */

export const metadata: Metadata = {
  title: 'B20 split replay — Corporate Action Guard',
  description:
    'What three integrations say about the same B20 holding after a 10:1 corporate action.',
};

const VERDICT_CLASS: Record<string, string> = {
  VERIFIED: 'b20-verdict b20-verdict--verified',
  WRONG: 'b20-verdict b20-verdict--wrong',
};

export default function B20ReplayPage() {
  const { asset, capability, pairing, replayedSplit, derivation, conformance } = replay;

  return (
    <AppShell environmentLabel="Base mainnet · read-only" currentPath="/b20">
      <div className="b20">
        {/* Stated before anything numeric, so nobody reads a number first and the label second. */}
        <div className="b20-banner" role="note">
          <span className="b20-banner__tag">RECORDED REPLAY</span>
          <span>
            Generated by <code>scripts/b20-e2e-proof.mjs</code> from a live Base mainnet read plus a
            replayed 10:1 split. Not live production state, and not an observed corporate action —
            no Coinbase asset has had one yet.
          </span>
        </div>

        <header className="b20-header">
          <h1>A 10:1 split, and three integrations that disagree</h1>
          <p className="b20-sub">
            Same asset, same holding, same moment. Two of these answers are wrong, neither reverts,
            and both reconcile against themselves.
          </p>
        </header>

        <section className="b20-panel" aria-labelledby="asset-heading">
          <h2 id="asset-heading">The asset, read live</h2>
          <dl className="b20-facts">
            <div>
              <dt>Asset</dt>
              <dd>
                {asset.displaySymbol} · {asset.onchainName}
              </dd>
            </div>
            <div>
              <dt>Identity</dt>
              <dd className="b20-mono">
                {asset.chainId}:{asset.address}
              </dd>
            </div>
            <div>
              <dt>Block</dt>
              <dd className="b20-mono">{asset.blockNumber ?? 'not read'}</dd>
            </div>
            <div>
              <dt>Observed multiplier</dt>
              <dd className="b20-mono">1.0 (no corporate action yet)</dd>
            </div>
          </dl>
          <p className="b20-note">
            Identity is <strong>(chainId, address)</strong>. The symbol is display only — it is
            mutable on chain, and an integration keyed on it loses the position when the issuer
            renames the token.
          </p>
        </section>

        <section className="b20-panel b20-panel--warn" aria-labelledby="cannot-heading">
          <h2 id="cannot-heading">What the chain will not tell us</h2>
          <p>
            <code className="b20-mono">newUIMultiplier()</code> is{' '}
            <strong>{capability.newUIMultiplier}</strong> — a B20 token is precompile-backed, and a
            selector this hardfork has not dialed reverts with exactly its own four bytes (
            <code className="b20-mono">{capability.selector}</code>).
          </p>
          <p className="b20-emphasis">{capability.consequence}</p>
          <p>
            The token-to-feed pairing is <strong>{pairing.reviewStatus}</strong>.{' '}
            {pairing.consequence}
          </p>
        </section>

        <section className="b20-panel" aria-labelledby="split-heading">
          <h2 id="split-heading">
            After the split <span className="b20-replay-tag">replayed</span>
          </h2>
          <p className="b20-sub">
            Holding <span className="b20-mono">{replayedSplit.rawDisplay}</span> raw units.
            Chainlink total-return price{' '}
            <span className="b20-mono">${replayedSplit.totalReturnPriceDisplay}</span> per token —
            unchanged by the split, because the multiplier is already inside it.
          </p>

          <div className="b20-table-scroll">
            <table className="b20-table">
              <caption className="b20-visually-hidden">
                Share count and position value reported by three integrations after a 10 to 1 split
              </caption>
              <thead>
                <tr>
                  <th scope="col">Integration</th>
                  <th scope="col">Shares</th>
                  <th scope="col">Value</th>
                  <th scope="col">Verdict</th>
                </tr>
              </thead>
              <tbody>
                {replayedSplit.rows.map((row) => (
                  <tr key={row.integration}>
                    <th scope="row">
                      {row.integration}
                      <span className="b20-why">{row.why}</span>
                    </th>
                    <td className="b20-mono">{row.shares}</td>
                    <td className="b20-mono">
                      {row.value === null ? (
                        '—'
                      ) : (
                        <>
                          <span className="b20-value">${row.value}</span>
                          {/* The exact scaled integer travels with the rounded display, because
                              formatting must never be the only record of a number. */}
                          <span className="b20-value-exact">{row.valueExact}</span>
                        </>
                      )}
                    </td>
                    <td>
                      {/* Never colour alone: the label carries the meaning on its own. */}
                      <span className={VERDICT_CLASS[row.verdict] ?? 'b20-verdict'}>
                        {row.verdict}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <p className="b20-emphasis">
            The double-multiplied answer is exactly {replayedSplit.errorFactor}× the correct one.
          </p>
        </section>

        <section className="b20-panel" aria-labelledby="math-heading">
          <h2 id="math-heading">Show the math</h2>
          <ol className="b20-steps">
            {derivation.map((step) => (
              <li key={step.label}>
                <span className="b20-step-label">{step.label}</span>
                <code className="b20-mono b20-step-expr">{step.expression}</code>
                <span className="b20-mono b20-step-result">= {step.result}</span>
              </li>
            ))}
          </ol>
          <p className="b20-note">
            Every step is recomputable by hand. The remainder floor discards gets its own line
            rather than a footnote — a holder short by one unit is owed an explanation.
          </p>
        </section>

        <section className="b20-panel" aria-labelledby="conformance-heading">
          <h2 id="conformance-heading">The suite that catches this</h2>
          <p>
            <strong>
              {conformance.scenariosPassed}/{conformance.scenariosTotal}
            </strong>{' '}
            scenarios pass against a correct integration, and{' '}
            <strong>
              {conformance.mutantsCaught}/{conformance.mutantsTotal}
            </strong>{' '}
            known integration defects are caught. A suite that only ever sees correct code proves
            nothing about itself.
          </p>
          <ul className="b20-mutants">
            {conformance.mutants.map((m) => (
              <li key={m.mutation}>
                <code className="b20-mono">{m.mutation}</code> caught by {m.scenario}
              </li>
            ))}
          </ul>
        </section>

        <section className="b20-panel b20-panel--boundary" aria-labelledby="not-heading">
          <h2 id="not-heading">What this does not claim</h2>
          <ul>
            {replay.notClaimed.map((claim) => (
              <li key={claim}>{claim}</li>
            ))}
          </ul>
        </section>

        <footer className="b20-footer">
          <span className="b20-mono">{replay.artifactDigest}</span>
          <span>run at {replay.runAt}</span>
        </footer>
      </div>
    </AppShell>
  );
}
